name: bujriwala
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Ensures compatibility with modern packages

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  cloud_firestore: ^5.4.4
  razorpay_flutter: ^1.3.7
  web3dart: ^2.7.3
  http: ^1.2.2
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  toastification: ^3.0.2  # Using alternative toast package
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  fluttertoast: ^8.2.4  # Ensures compatibility with other dependencies
